packages:
  - 'packages/*'
  - docs
overrides:
  coralite: 'workspace:*'
peerDependencyRules:
  allowedVersions:
    coralite: "*"
packageExtensions:
  sass-embedded:
    peerDependencies:
      source-map-js: "*"
    peerDependenciesMeta:
      source-map-js:
        optional: true
onlyBuiltDependencies:
  - simple-git-hooks
