packages:
  - packages/*
  - website

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  simple-git-hooks: true

minimumReleaseAgeExclude:
  - coralite-plugin-aggregation@0.12.0
  - coralite-plugin-aggregation@0.12.1

onlyBuiltDependencies:
  - "@parcel/watcher"
  - simple-git-hooks
  - esbuild
  - playwright-firefox
