packages:
  - packages/*
  - website

onlyBuiltDependencies:
  - '@parcel/watcher'
  - simple-git-hooks
  - esbuild
  - playwright-firefox

packageExtensions:
  coralite-scripts:
    optionalDependencies:
      coralite: npm:coralite@0.18.3