name: Publish to Codeberg

on:
  push:
    tags:
      - "*-v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: codeberg-small
    container:
      image: "guergeiro/pnpm:lts-latest-slim"
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Cache pnpm modules
        uses: https://code.forgejo.org/actions/cache@v3
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish to Codeberg
        env:
          CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          node packages/coralite-release/bin/publish.js --registry codeberg --tag-ref "${{ github.ref_name }}"