name: Release to NPM

on:
  push:
    tags:
      - "*-v*"

jobs:
  publish:
    runs-on: codeberg-tiny-lazy
    container:
      image: "guergeiro/pnpm:22-10-slim"
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Extract Package Name
        run: |
          PACKAGE_NAME=$(echo ${{ github.ref_name }} | sed -E 's/-v[0-9]+\.[0-9]+\.[0-9]+.*//')
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV

      - name: Cache pnpm modules
        uses: https://code.forgejo.org/actions/cache@v3
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install pnpm
        run: |
          npm install -g corepack@latest
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm --filter "${{ env.PACKAGE_NAME }}..." run build

      - name: Publish to NPM
        run: |
          pnpm --filter "${{ env.PACKAGE_NAME }}" publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}