/**
 * @import {
 *  CoraliteClientPluginDisconnectedCallback,
 *  CoraliteClientPluginAfterComponentRenderCallback,
 *  CoraliteClientPluginBeforeComponentRenderCallback
 * } from '../types/plugin.js'
 */

import { createReadOnlyProxy } from './utils/core.js'
import { processHTML } from './utils/client/inject.js'

const BOOLEAN_ATTRIBUTES = new Set([
  'allowfullscreen',
  'async',
  'autofocus',
  'autoplay',
  'checked',
  'controls',
  'default',
  'defer',
  'disabled',
  'formnovalidate',
  'hidden',
  'inert',
  'ismap',
  'itemscope',
  'loop',
  'multiple',
  'muted',
  'nomodule',
  'novalidate',
  'open',
  'playsinline',
  'readonly',
  'required',
  'reversed',
  'selected',
  'truespeed'
])

/**
 * Coerces a value to a specified type.
 * Supports Number, Boolean, and String.
 * @param {any} value - The value to coerce.
 * @param {Function|string} type - The target type (Constructor or string name).
 * @returns {any} The coerced value.
 */
export function coerce (value, type) {
  if (value === null || value === undefined) {
    return value
  }
  if (type === Number || type === 'Number') {
    return Number(value)
  }
  if (type === Boolean || type === 'Boolean') {
    if (value === '') {
      return true
    }
    return value !== 'false' && value !== null
  }
  if (type === String || type === 'String') {
    return String(value)
  }
  return value
}

/**
 * @typedef {Object} CoraliteComponentOptions
 * @property {string} componentId - The unique identifier for the component.
 * @property {string} [templateHTML] - The raw HTML string for imperative mounting.
 * @property {Object} [defaultValues] - The initial state values extracted from the server data block.
 * @property {Object} [attributes] - Schema for coercing HTML attributes into typed primitives.
 * @property {Object.<string, Function>} [getters] - Pure functions for derived state, supporting Promises.
 * @property {Object.<string, Function>} [slots] - Transformation functions for projected Light DOM.
 * @property {Function} [client] - The client-side controller logic.
 * @property {Object} [hydrationMap] - AST mapping for reactive text nodes, attributes, and refs.
 */

/**
 * Base class for all Coralite custom elements.
 *
 * @augments HTMLElement
 */
export class CoraliteElement extends HTMLElement {
  /**
   * Initializes a new instance of the CoraliteElement.
   * Sets up internal state trackers, binding collections, and hook registries.
   */
  constructor () {
    super()
    /**
     * Controls native teardown of event listeners and async fetches upon disconnection.
     * @type {AbortController|null}
     * @protected
     */
    this._abortController = null

    /**
     * @type {Map<string, Set<Function>>|null}
     * @protected
     */
    this._observers = new Map()

    /**
     * Flag to detect infinite loops in state observation callback.
     * @type {boolean}
     * @protected
     */
    this._isExecutingObserver = false

    /**
     * A globally unique, deterministic identifier (e.g., `my-comp-0`).
     * @type {string|null}
     * @protected
     */
    this._instanceId = null

    /**
     * The unified, deeply reactive proxy holding attributes, data, and getters.
     * @type {Object|null}
     * @protected
     */
    this._state = null

    /**
     * The collection of DOM nodes mapped to template tokens and attributes.
     * @type {Array<{type: string, node: Node, template?: string, name?: string}>}
     * @protected
     */
    this._bindings = []

    /**
     * Flag to prevent multiple synchronous state mutations from triggering multiple DOM paints.
     * @type {boolean}
     * @protected
     */
    this._isUpdatePending = false

    /**
     * A unique Symbol generated per render cycle to prevent async getter race conditions.
     * @type {symbol|null}
     * @protected
     */
    this._currentRenderVersion = null

    /**
     * @type {MutationObserver|null}
     * @protected
     */
    this._observer = null

    /**
     * Hook to fetch globally registered Phase-2 plugin contexts.
     * @type {Function|null}
     * @protected
     */
    this._clientContextGetter = null

    /**
     * Tracks AbortControllers specifically for cancelling stale async getters.
     * @type {Object.<string, AbortController>|null}
     * @protected
     */
    this._getterAbortControllers = null

    /**
     * Internal lifecycle hooks injected by registered Coralite plugins.
     * @type {{
     *   onBeforeComponentRender: Array<CoraliteClientPluginBeforeComponentRenderCallback>,
     *   onAfterComponentRender: Array<CoraliteClientPluginAfterComponentRenderCallback>,
     *   onDisconnected: Array<CoraliteClientPluginDisconnectedCallback>
     * }}
     * @protected
     */
    this._hooks = {
      onBeforeComponentRender: [],
      onAfterComponentRender: [],
      onDisconnected: []
    }

    /**
     * The definition and schema of the component generated by the compiler.
     * @type {CoraliteComponentOptions|null}
     */
    this.componentOptions = null

    /**
     * Hydrated data passed from the server.
     * @type {Object|null}
     * @protected
     */
    this._hydrationData = null
  }

  /**
   * Invoked natively when the element is added to the document.
   * Handles the architectural split between Declarative (SSR) and Imperative (JS) components.
   * Orchestrates template injection, instance ID generation, and state/binding setup.
   */
  connectedCallback () {
    this._abortController = new AbortController()
    this._observers = new Map()
    this._isExecutingObserver = false

    if (!this.componentOptions) {
      return
    }

    // Declarative components receive a data-cid from the server.
    // Imperative components (created via document.createElement) do not.
    const isImperative = !this.hasAttribute('data-cid')

    // Imperative Flow: Manually stamp the template and project the Light DOM.
    if (isImperative && this.componentOptions.templateHTML) {
      const originalLightDOM = Array.from(this.childNodes)
      this.innerHTML = processHTML(this.componentOptions.templateHTML)

      if (originalLightDOM.length > 0) {
        const slots = this.querySelectorAll('slot')
        slots.forEach(slot => {
          const slotName = slot.getAttribute('name') || 'default'
          const matchingNodes = originalLightDOM.filter(node => {
            // @ts-ignore
            const nodeSlot = (node.getAttribute && node.getAttribute('slot')) || 'default'
            return nodeSlot === slotName
          })
          matchingNodes.forEach(n => slot.appendChild(n))
        })
      }
    }

    // Establish the Deterministic Instance ID
    if (this.hasAttribute('data-cid')) {
      this._instanceId = this.getAttribute('data-cid')
    } else {
      // Fallback counter for imperatively created components
      // @ts-ignore
      window.__coralite_instanceCounters = window.__coralite_instanceCounters || {}
      const prefix = this.componentOptions.componentId
      // @ts-ignore
      if (window.__coralite_instanceCounters[prefix] === undefined) {
        // @ts-ignore
        window.__coralite_instanceCounters[prefix] = 0
      }
      // @ts-ignore
      this._instanceId = `${prefix}-${window.__coralite_instanceCounters[prefix]++}`
    }

    if (isImperative) {
      this.setAttribute('data-cid', this._instanceId)
    }

    this._setupState()
    this._setupBindings()
    this._init(isImperative)
  }

  /**
   * Invoked natively when the element is removed from the document.
   * Aborts pending requests and triggers `onDisconnected` plugin hooks
   * to ensure external libraries (e.g., Observers) do not cause memory leaks.
   * @this {any}
   */
  disconnectedCallback () {
    if (this._abortController) {
      this._abortController.abort()
    }

    if (this._observers) {
      this._observers.clear()
      this._observers = null
    }

    if (!this.componentOptions) {
      return
    }

    for (const hook of this._hooks.onDisconnected) {
      hook({
        state: this._state,
        instanceId: this._instanceId,
        componentId: this.componentOptions.componentId,
        element: this,
        options: this.componentOptions
      })
    }
  }

  /**
   * Invoked natively when an observed HTML attribute changes.
   * Coerces the raw string value based on the component's attribute schema
   * and synchronizes it into the reactive state proxy.
   * @param {string} name - The kebab-case name of the attribute.
   * @param {string|null} oldVal - The previous value.
   * @param {string|null} newVal - The new value.
   */
  attributeChangedCallback (name, oldVal, newVal) {
    if (!this._state || oldVal === newVal || name === 'data-cid') {
      return
    }
    const camelName = name.replace(/-([a-z])/g, (g) => g[1].toUpperCase())
    const schema = this.componentOptions.attributes?.[camelName] || this.componentOptions.attributes?.[name]
    const value = schema ? coerce(newVal, schema.type || schema) : newVal

    this._state[camelName] = value
  }

  /**
   * Constructs the unified state object.
   * Merges `defaultValues`, JSON hydration payloads, and DOM attributes.
   * Defines getters (wrapping state in a Read-Only proxy) and applies the final Read/Write Proxy.
   * @this {any}
   * @private
   */
  _setupState () {
    const options = this.componentOptions
    const target = { ...options.defaultValues }

    /** @type {Array<{name: string, element: HTMLElement}>} */
    const refs = []
    if (options.hydrationMap && options.hydrationMap.refs) {
      for (const ref of options.hydrationMap.refs) {
        const uniqueRefValue = `${this._instanceId}__${ref.name}`

        if (!target[`ref_${ref.name}`]) {
          target[`ref_${ref.name}`] = uniqueRefValue
        }

        const node = this.getNodeByPath(ref.path)
        if (node) {
          if (node.setAttribute) {
            node.setAttribute('ref', uniqueRefValue)
          }
          refs.push({
            name: ref.name,
            element: node
          })
        }
      }
    }

    // Process initial attributes mapping
    for (const attr of this.attributes) {
      if (attr.name === 'data-cid') {
        continue
      }
      const camelName = attr.name.replace(/-([a-z])/g, (g) => g[1].toUpperCase())
      const schema = options.attributes?.[camelName] || options.attributes?.[attr.name]
      target[camelName] = schema ? coerce(attr.value, schema.type || schema) : attr.value
    }

    // Hydrate data() block results from the SSR payload
    if (this._hydrationData && this._hydrationData[this._instanceId]) {
      Object.assign(target, this._hydrationData[this._instanceId])
    }

    // Trigger Before-Render hooks BEFORE state is proxied, allowing plugins to inject reactive data
    for (const hook of this._hooks.onBeforeComponentRender) {
      hook({
        state: target,
        instanceId: this._instanceId,
        componentId: this.componentOptions.componentId,
        refs,
        element: this,
        options: this.componentOptions
      })
    }

    // Define derived state getters with isolation controllers
    this._getterAbortControllers = {}
    for (const [key, getter] of Object.entries(options.getters || {})) {
      Object.defineProperty(target, key, {
        get: () => {
          if (this._getterAbortControllers[key]) {
            this._getterAbortControllers[key].abort()
          }
          this._getterAbortControllers[key] = new AbortController()

          // Enforce "Dual-Proxy" safety: Getters cannot mutate state
          const roState = createReadOnlyProxy(this._state)
          return getter(roState, { signal: this._getterAbortControllers[key].signal })
        },
        enumerable: true,
        configurable: true
      })
    }

    this._state = this._createReactiveProxy(target)
  }

  /**
   * Wraps the state target in a reactive Proxy.
   * Intercepts property setters to automatically batch and schedule DOM updates.
   * @param {Object} target - The state dictionary.
   * @returns {Proxy} The reactive state proxy.
   * @private
   */
  _createReactiveProxy (target) {
    const self = this
    return new Proxy(target, {
      set (t, p, v) {
        const oldValue = t[p]
        if (oldValue === v) {
          return true
        }

        if (typeof p === 'string') {
          // Dev mode safeguard for infinite loop state mutations
          const mode = (typeof window !== 'undefined' && window['__coralite__'] && window['__coralite__'].mode) || 'production'

          if (mode === 'development' && self._isExecutingObserver) {
            console.warn('[Coralite Warning]: State mutation detected inside an observe() callback. This can cause infinite reactivity loops. Use getters for derived state instead.')
          }
        }

        t[p] = v
        self._scheduleUpdate()

        // Trigger any observers registered for this property
        if (typeof p === 'string' && self._observers && self._observers.has(p)) {
          const wasExecuting = self._isExecutingObserver
          self._isExecutingObserver = true
          try {
            self._observers.get(p).forEach(cb => cb(v, oldValue))
          } finally {
            self._isExecutingObserver = wasExecuting
          }
        }

        return true
      }
    })
  }

  /**
   * Traverses the DOM tree using an AST-generated path index array.
   * Allows O(1) element lookups without relying on querySelectors or classes.
   * @param {number[]} path - Array of childNode indices (e.g., `[0, 1, 2]`).
   * @returns {Node|null} The physical DOM node, or null if traversal fails.
   */
  getNodeByPath (path) {
    let node = this
    for (const index of path) {
      if (!node) {
        return null
      }
      // @ts-ignore
      node = node.childNodes[index]
    }
    return node
  }

  /**
   * Initializes DOM bindings based on the compiler's hydration map.
   * Caches physical DOM references to text nodes and attributes that contain template tokens.
   * @private
   */
  _setupBindings () {
    this._bindings = []
    const map = this.componentOptions.hydrationMap
    if (!map) {
      return
    }

    if (map.texts) {
      for (const item of map.texts) {
        const node = this.getNodeByPath(item.path)
        if (node) {
          this._bindings.push({
            type: item.type || 'text',
            node,
            template: item.template
          })
        }
      }
    }

    if (map.attributes) {
      for (const item of map.attributes) {
        const node = this.getNodeByPath(item.path)
        if (node) {
          this._bindings.push({
            type: 'attribute',
            node,
            name: item.name,
            template: item.template
          })
        }
      }
    }
  }

  /**
   * Schedules a DOM update in the next microtask queue.
   * This guarantees that multiple synchronous state mutations result in only one render pass.
   * @private
   */
  _scheduleUpdate () {
    if (this._isUpdatePending) {
      return
    }
    this._isUpdatePending = true
    queueMicrotask(() => {
      this._updateDOM()
      this._isUpdatePending = false
    })
  }

  /**
   * Performs the physical DOM update and resolves template tokens.
   * **Async Safety:** Implements a Symbol-based locking mechanism (`renderVersion`)
   * to guarantee that if state mutates while an async getter is pending, the stale
   * Promise will be discarded, preventing DOM race conditions.
   * @this {any}
   * @private
   */
  _updateDOM () {
    // Create a unique lock for this specific render cycle
    const renderVersion = Symbol()
    this._currentRenderVersion = renderVersion

    // Extract unique tokens to prevent double-reading and accidental aborts
    /** @type {Set<string>} */
    const requiredTokens = new Set()
    for (const binding of this._bindings) {
      binding.template.replace(/\{\{\s*(.+?)\s*\}\}/g, (_, key) => {
        requiredTokens.add(key)
        return ''
      })
    }

    const evaluatedTokens = {}
    let hasPromise = false

    // Evaluate getters exactly once per render cycle
    for (const key of requiredTokens) {
      let val = this._state[key]
      if (typeof val === 'function') {
        val = val(this._state)
      }
      evaluatedTokens[key] = val
      if (val instanceof Promise) {
        hasPromise = true
      }
    }

    // The DOM Mutator Function
    const applyBindings = (tokenValues) => {
      // Race Condition Lock: Abort if a newer render cycle has already begun
      if (this._currentRenderVersion !== renderVersion) {
        return
      }

      for (const binding of this._bindings) {
        const hydratedValue = binding.template.replace(/\{\{\s*(.+?)\s*\}\}/g, (_, key) => {
          return tokenValues[key] ?? ''
        })

        if (binding.type === 'text') {
          if (binding.node.textContent !== hydratedValue) {
            binding.node.textContent = hydratedValue
          }
        } else if (binding.type === 'html') {
          /** @type {HTMLElement} */
          // @ts-ignore
          const element = binding.node

          if (element.innerHTML !== hydratedValue) {
            element.innerHTML = hydratedValue
          }
        } else if (binding.type === 'attribute') {
          /** @type {HTMLElement} */
          // @ts-ignore
          const element = binding.node

          if (BOOLEAN_ATTRIBUTES.has(binding.name)) {
            const isFalsy = hydratedValue === '' || hydratedValue === 'false' || hydratedValue === 'null' || hydratedValue === '0' || hydratedValue === 'undefined'
            if (isFalsy) {
              element.removeAttribute(binding.name)
            } else {
              element.setAttribute(binding.name, '')
            }
          } else {
            if (element.getAttribute(binding.name) !== hydratedValue) {
              element.setAttribute(binding.name, hydratedValue)
            }
          }
        }
      }

      this._processSlots()

      // Trigger After-Render hooks ONLY after the physical DOM is stable
      for (const hook of this._hooks.onAfterComponentRender) {
        hook({
          state: this._state,
          instanceId: this._instanceId,
          componentId: this.componentOptions.componentId,
          element: this,
          options: this.componentOptions
        })
      }

      // @ts-ignore
      if (window.__coralite__ && window.__coralite__.lifecycle) {
        // @ts-ignore
        window.__coralite__.lifecycle._markInstanceRendered(this)
      }
    }

    // Await Promises or Apply Synchronously
    if (hasPromise) {
      const keys = Object.keys(evaluatedTokens)
      const promises = keys.map(k => Promise.resolve(evaluatedTokens[k]))

      Promise.all(promises).then(resolvedValues => {
        const resolvedMap = {}
        keys.forEach((k, i) => {
          resolvedMap[k] = resolvedValues[i]
        })
        applyBindings(resolvedMap)
      }).catch(e => {
        if (e.name !== 'AbortError') {
          console.error('Coralite Async Getter Error:', e)
        }
      })
    } else {
      applyBindings(evaluatedTokens)
    }
  }

  /**
   * Evaluates and projects Light DOM elements into their respective `<slot>` nodes.
   * Invokes component-specific slot transformation functions.
   * @private
   */
  _processSlots () {
    const slots = this.componentOptions.slots
    if (!slots || Object.keys(slots).length === 0) {
      return
    }

    const slotElements = this.querySelectorAll('slot')
    slotElements.forEach(slotEl => {
      const slotName = slotEl.getAttribute('name') || 'default'
      const slotFn = slots[slotName]

      if (slotFn) {
        // @ts-ignore
        if (!slotEl._originalNodes) {
          // @ts-ignore
          slotEl._originalNodes = Array.from(slotEl.childNodes).map(n => n.cloneNode(true))
        }

        // @ts-ignore
        const result = slotFn(slotEl._originalNodes, this._state)

        if (result === undefined) {
          return
        }

        if (result === null || result === '' || (Array.isArray(result) && result.length === 0)) {
          slotEl.innerHTML = ''
          return
        }

        if (typeof result === 'string') {
          slotEl.innerHTML = result
        } else if (Array.isArray(result)) {
          slotEl.replaceChildren(...result)
        }
      }
    })
  }

  /**
   * The final initialization pipeline.
   * Injects globally registered client plugins into the local context payload,
   * triggers the initial DOM render, and invokes the user's `script()` logic.
   * @param {boolean} [isImperative=false] - If true, initial render runs synchronously.
   * @private
   */
  async _init (isImperative = false) {
    const self = this

    const signal = this._abortController.signal

    // Hook up AbortSignal to nuke/cleanup observers to prevent memory leaks
    signal.addEventListener('abort', () => {
      if (self._observers) {
        self._observers.clear()
        self._observers = null
      }
    })

    const observe = (key, callback) => {
      if (!self._observers) {
        return
      }
      if (!self._observers.has(key)) {
        self._observers.set(key, new Set())
      }
      self._observers.get(key).add(callback)

      signal.addEventListener('abort', () => {
        if (self._observers && self._observers.has(key)) {
          self._observers.get(key).delete(callback)
        }
      })
    }

    /**
     * The context payload injected into the user's script block.
     * @type {Object}
     */
    let localContext = {
      instanceId: this._instanceId,
      state: this._state,
      root: this,
      signal: this._abortController.signal,
      refs (id) {
        const refId = self._state[`ref_${id}`]
        if (!refId && typeof refId !== 'string') {
          return null
        }
        return self.querySelector(`[ref="${refId}"]`)
      },
      observe
    }

    if (typeof this._clientContextGetter === 'function') {
      localContext = await this._clientContextGetter(localContext)
    }

    if (isImperative) {
      this._updateDOM()
    } else {
      this._scheduleUpdate()
    }

    if (window['__coralite__'] && window['__coralite__'].components) {
      window['__coralite__'].components[this._instanceId] = {
        state: this._state,
        tagName: this.tagName.toLowerCase(),
        componentId: this.componentOptions.componentId
      }
    }

    if (this.componentOptions.client) {
      try {
        await this.componentOptions.client(localContext)
      } catch (error) {
        console.error(`Coralite Error: Component "${this.componentOptions.componentId}" script failed:`, error)
        if (window['__coralite__'] && window['__coralite__'].components) {
          const fatalError = new Error(`Coralite Component Error: Component "${this.componentOptions.componentId}" (${this._instanceId}) client() block failed: ${error.message}`)
          fatalError.stack = error.stack

          if (typeof window['showCoraliteError'] === 'function') {
            window['showCoraliteError'](fatalError)
          } else {
            const overlay = document.createElement('div')
            overlay.style = 'position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(255,0,0,0.9);color:white;padding:20px;z-index:10000;font-family:monospace;white-space:pre-wrap;overflow:auto;'
            overlay.innerHTML = `<h1>Coralite Component Error</h1><p>${fatalError.message}</p><pre>${fatalError.stack}</pre>`
            document.body.appendChild(overlay)
          }
          throw fatalError
        }
      }
    }

    // @ts-ignore
    if (window.__coralite__ && window.__coralite__.lifecycle) {
      // @ts-ignore
      window.__coralite__.lifecycle._markInstanceReady(this)
    }
  }
}

/**
 * Factory function to create a Coralite element class.
 * It dynamically defines the class, including observed attributes and hook initialization.
 * @param {CoraliteComponentOptions} options - Component options and metadata.
 * @param {Function|null} [contextGetter=null] - Optional function to retrieve client-side plugin context.
 * @param {Object} [hooks={}] - Lifecycle hooks to register.
 * @param {Array<CoraliteClientPluginBeforeComponentRenderCallback>} [hooks.onBeforeComponentRender] - Hooks to run before render.
 * @param {Array<CoraliteClientPluginAfterComponentRenderCallback>} [hooks.onAfterComponentRender] - Hooks to run after render.
 * @param {Array<CoraliteClientPluginDisconnectedCallback>} [hooks.onDisconnected] - Hooks to run after render.
 * @param {Object|null} [hydrationData=null] - Hydrated data passed from the server.
 * @returns {typeof CoraliteElement} A new CoraliteElement subclass.
 */
export function createCoraliteClass (options, contextGetter = null, hooks = {}, hydrationData = null) {
  return class extends CoraliteElement {
    /**
     * The attributes to observe for changes.
     * @returns {string[]} Array of attribute names.
     */
    static get observedAttributes () {
      if (!options.attributes) {
        return []
      }
      return Object.keys(options.attributes).map(key => key.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
      )
    }

    /**
     * Initializes the dynamic Coralite element.
     */
    constructor () {
      super()

      const self = this
      // Override dispatchEvent to intercept all CustomEvents
      const originalDispatchEvent = this.dispatchEvent
      this.dispatchEvent = function (event) {
        if (window['__coralite__'] && window['__coralite__'].events && event instanceof CustomEvent) {
          window['__coralite__'].events.push({
            name: event.type,
            detail: event.detail,
            sourceComponentId: self._instanceId,
            sourceTagName: self.tagName.toLowerCase(),
            timestamp: Date.now()
          })
        }
        return originalDispatchEvent.call(this, event)
      }
      this.componentOptions = options
      this._clientContextGetter = contextGetter
      this._hydrationData = hydrationData
      this._hooks = {
        onBeforeComponentRender: hooks.onBeforeComponentRender || [],
        onAfterComponentRender: hooks.onAfterComponentRender || [],
        onDisconnected: hooks.onDisconnected || []
      }
    }
  }
}
