/**
 * @import {
 *   CoraliteInstance as _CoraliteInstance,
 *   HTMLData as _HTMLData,
 *   CoraliteFilePath as _CoraliteFilePath,
 *   CoralitePath as _CoralitePath,
 *   CoraliteConfig as _CoraliteConfig,
 *   CoralitePage as _CoralitePage,
 *   CoraliteProperties as _CoraliteProperties,
 *   CoraliteStaticAsset as _CoraliteStaticAsset,
 *   CoraliteErrorData as _CoraliteErrorData,
 *   CoraliteOnError as _CoraliteOnError,
 *   CoraliteSession as _CoraliteSession,
 *   CoraliteBuildOptions as _CoraliteBuildOptions,
 *   CoraliteBuildResult as _CoraliteBuildResult,
 *   CoraliteSaveResult as _CoraliteSaveResult,
 *   CoraliteBuildCallback as _CoraliteBuildCallback,
 *   ComponentElementOptions as _ComponentElementOptions,
 *   CoraliteElement as _CoraliteElement,
 *   RawCoraliteElement as _RawCoraliteElement,
 *   CoraliteTextNode as _CoraliteTextNode,
 *   RawCoraliteTextNode as _RawCoraliteTextNode,
 *   CoraliteComment as _CoraliteComment,
 *   RawCoraliteComment as _RawCoraliteComment,
 *   CoraliteDirective as _CoraliteDirective,
 *   RawCoraliteDirective as _RawCoraliteDirective,
 *   CoraliteAnyNode as _CoraliteAnyNode,
 *   CoraliteComponentRoot as _CoraliteComponentRoot,
 *   RawCoraliteComponentRoot as _RawCoraliteComponentRoot,
 *   CoraliteContentNode as _CoraliteContentNode,
 *   CoraliteComponent as _CoraliteComponent,
 *   CoraliteResult as _CoraliteResult,
 *   ParseHTMLResult as _ParseHTMLResult,
 *   CoraliteToken as _CoraliteToken,
 *   CoraliteAttributeToken as _CoraliteAttributeToken,
 *   CoraliteTextNodeToken as _CoraliteTextNodeToken,
 *   CoraliteRef as _CoraliteRef,
 *   CoraliteComponentValues as _CoraliteComponentValues,
 *   Attribute as _Attribute,
 *   CoraliteComponentResult as _CoraliteComponentResult,
 *   CoraliteModule as _CoraliteModule,
 *   CoraliteModuleDefinitions as _CoraliteModuleDefinitions,
 *   CoraliteModuleDefinition as _CoraliteModuleDefinition,
 *   CoraliteModuleSlotElement as _CoraliteModuleSlotElement,
 *   CoraliteModuleScript as _CoraliteModuleScript,
 *   CoraliteModuleProperties as _CoraliteModuleProperties,
 *   CoraliteModulePropertiesFunction as _CoraliteModulePropertiesFunction,
 *   CoraliteModuleSlotFunction as _CoraliteModuleSlotFunction,
 *   CoraliteModuleDataFunction as _CoraliteModuleDataFunction,
 *   CoraliteModuleGetterFunction as _CoraliteModuleGetterFunction,
 *   CoraliteCollection as _CoraliteCollection,
 *   CoraliteCollectionItem as _CoraliteCollectionItem,
 *   CoraliteCollectionCallbackResult as _CoraliteCollectionCallbackResult,
 *   CoraliteCollectionEventResult as _CoraliteCollectionEventResult,
 *   CoraliteCollectionEventSet as _CoraliteCollectionEventSet,
 *   CoraliteCollectionEventDelete as _CoraliteCollectionEventDelete,
 *   CoraliteCollectionEventUpdate as _CoraliteCollectionEventUpdate,
 *   CoralitePlugin as _CoralitePlugin,
 *   CoralitePluginContext as _CoralitePluginContext,
 *   CoralitePluginExportFunction as _CoralitePluginExportFunction,
 *   CoralitePluginInstance as _CoralitePluginInstance,
 *   CoralitePluginPageSetCallback as _CoralitePluginPageSetCallback,
 *   CoralitePluginPageUpdateCallback as _CoralitePluginPageUpdateCallback,
 *   CoralitePluginPageDeleteCallback as _CoralitePluginPageDeleteCallback,
 *   CoralitePluginComponentCallback as _CoralitePluginComponentCallback,
 *   CoralitePluginAfterPageRenderCallback as _CoralitePluginAfterPageRenderCallback,
 *   ScriptContent as _ScriptContent,
 *   ScriptPlugin as _ScriptPlugin,
 *   InstanceContext as _InstanceContext,
 *   CoraliteScriptContext as _CoraliteScriptContext,
 *   ScriptPluginHelperGlobalContext as _ScriptPluginHelperGlobalContext,
 *   ScriptPluginHelperGlobalInstance as _ScriptPluginHelperGlobalInstance,
 *   ScriptPluginHelperLocalInstance as _ScriptPluginHelperLocalInstance,
 *   ScriptImport as _ScriptImport
 * } from '../types/index.js'
 */

/**
 * @typedef {_CoraliteInstance} CoraliteInstance
 * @typedef {_CoraliteInstance} Coralite
 * @typedef {_HTMLData} HTMLData
 * @typedef {_CoraliteFilePath} CoraliteFilePath
 * @typedef {_CoralitePath} CoralitePath
 * @typedef {_CoraliteConfig} CoraliteConfig
 * @typedef {_CoralitePage} CoralitePage
 * @typedef {_CoraliteProperties} CoraliteProperties
 * @typedef {_CoraliteStaticAsset} CoraliteStaticAsset
 * @typedef {_CoraliteErrorData} CoraliteErrorData
 * @typedef {_CoraliteOnError} CoraliteOnError
 * @typedef {_CoraliteSession} CoraliteSession
 * @typedef {_CoraliteBuildOptions} CoraliteBuildOptions
 * @typedef {_CoraliteBuildResult} CoraliteBuildResult
 * @typedef {_CoraliteSaveResult} CoraliteSaveResult
 * @typedef {_CoraliteBuildCallback} CoraliteBuildCallback
 * @typedef {_ComponentElementOptions} ComponentElementOptions
 * @typedef {_CoraliteElement} CoraliteElement
 * @typedef {_RawCoraliteElement} RawCoraliteElement
 * @typedef {_CoraliteTextNode} CoraliteTextNode
 * @typedef {_RawCoraliteTextNode} RawCoraliteTextNode
 * @typedef {_CoraliteComment} CoraliteComment
 * @typedef {_RawCoraliteComment} RawCoraliteComment
 * @typedef {_CoraliteDirective} CoraliteDirective
 * @typedef {_RawCoraliteDirective} RawCoraliteDirective
 * @typedef {_CoraliteAnyNode} CoraliteAnyNode
 * @typedef {_CoraliteComponentRoot} CoraliteComponentRoot
 * @typedef {_RawCoraliteComponentRoot} RawCoraliteComponentRoot
 * @typedef {_CoraliteContentNode} CoraliteContentNode
 * @typedef {_CoraliteComponent} CoraliteComponent
 * @typedef {_CoraliteResult} CoraliteResult
 * @typedef {_ParseHTMLResult} ParseHTMLResult
 * @typedef {_CoraliteToken} CoraliteToken
 * @typedef {_CoraliteAttributeToken} CoraliteAttributeToken
 * @typedef {_CoraliteTextNodeToken} CoraliteTextNodeToken
 * @typedef {_CoraliteRef} CoraliteRef
 * @typedef {_CoraliteComponentValues} CoraliteComponentValues
 * @typedef {_Attribute} Attribute
 * @typedef {_CoraliteComponentResult} CoraliteComponentResult
 * @typedef {_CoraliteModule} CoraliteModule
 * @typedef {_CoraliteModuleDefinitions} CoraliteModuleDefinitions
 * @typedef {_CoraliteModuleDefinition} CoraliteModuleDefinition
 * @typedef {_CoraliteModuleSlotElement} CoraliteModuleSlotElement
 * @typedef {_CoraliteModuleScript} CoraliteModuleScript
 * @typedef {_CoraliteModuleProperties} CoraliteModuleProperties
 * @typedef {_CoraliteModulePropertiesFunction} CoraliteModulePropertiesFunction
 * @typedef {_CoraliteModuleSlotFunction} CoraliteModuleSlotFunction
 * @typedef {_CoraliteModuleDataFunction} CoraliteModuleDataFunction
 * @typedef {_CoraliteModuleGetterFunction} CoraliteModuleGetterFunction
 * @typedef {_CoraliteCollection} CoraliteCollection
 * @typedef {_CoraliteCollectionItem} CoraliteCollectionItem
 * @typedef {_CoraliteCollectionCallbackResult} CoraliteCollectionCallbackResult
 * @typedef {_CoraliteCollectionEventResult} CoraliteCollectionEventResult
 * @typedef {_CoraliteCollectionEventSet} CoraliteCollectionEventSet
 * @typedef {_CoraliteCollectionEventDelete} CoraliteCollectionEventDelete
 * @typedef {_CoraliteCollectionEventUpdate} CoraliteCollectionEventUpdate
 * @typedef {_CoralitePlugin} CoralitePlugin
 * @typedef {_CoralitePluginContext} CoralitePluginContext
 * @typedef {_CoralitePluginExportFunction} CoralitePluginExportFunction
 * @typedef {_CoralitePluginInstance} CoralitePluginInstance
 * @typedef {_CoralitePluginPageSetCallback} CoralitePluginPageSetCallback
 * @typedef {_CoralitePluginPageUpdateCallback} CoralitePluginPageUpdateCallback
 * @typedef {_CoralitePluginPageDeleteCallback} CoralitePluginPageDeleteCallback
 * @typedef {_CoralitePluginComponentCallback} CoralitePluginComponentCallback
 * @typedef {_CoralitePluginAfterPageRenderCallback} CoralitePluginAfterPageRenderCallback
 * @typedef {_ScriptContent} ScriptContent
 * @typedef {_ScriptPlugin} ScriptPlugin
 * @typedef {_InstanceContext} InstanceContext
 * @typedef {_CoraliteScriptContext} CoraliteScriptContext
 * @typedef {_ScriptPluginHelperGlobalContext} ScriptPluginHelperGlobalContext
 * @typedef {_ScriptPluginHelperGlobalInstance} ScriptPluginHelperGlobalInstance
 * @typedef {_ScriptPluginHelperLocalInstance} ScriptPluginHelperLocalInstance
 * @typedef {_ScriptImport} ScriptImport
 */

import { createCoralite } from './coralite.js'

export * from './html.js'
export * from './utils.js'
export * from './plugin.js'
export * from './config.js'
export * from './type-helper.js'
export * from './errors.js'
export * from './dom.js'

export { createCoralite }
export default createCoralite
