export const validTags = {
  a: true,
  abbr: true,
  acronym: true, // Deprecated
  address: true,
  area: true,
  article: true,
  aside: true,
  audio: true,
  b: true,
  base: true,
  bdi: true,
  bdo: true,
  big: true, // Deprecated
  blockquote: true,
  body: true,
  br: true,
  button: true,
  canvas: true,
  caption: true,
  center: true, // Deprecated
  cite: true,
  code: true,
  col: true,
  colgroup: true,
  data: true,
  datalist: true,
  dd: true,
  del: true,
  details: true,
  dfn: true,
  dialog: true,
  dir: true, // Deprecated
  div: true,
  dl: true,
  dt: true,
  em: true,
  embed: true,
  fencedframe: true, // Experimental
  fieldset: true,
  figcaption: true,
  figure: true,
  font: true, // Deprecated
  footer: true,
  form: true,
  frame: true, // Deprecated
  frameset: true, // Deprecated
  h1: true,
  h2: true,
  h3: true,
  h4: true,
  h5: true,
  h6: true,
  head: true,
  header: true,
  hgroup: true,
  hr: true,
  html: true,
  i: true,
  iframe: true,
  img: true,
  input: true,
  ins: true,
  kbd: true,
  label: true,
  legend: true,
  li: true,
  link: true,
  main: true,
  map: true,
  mark: true,
  marquee: true, // Deprecated
  menu: true,
  meta: true,
  meter: true,
  nav: true,
  nobr: true, // Deprecated
  noembed: true, // Deprecated
  noframes: true, // Deprecated
  noscript: true,
  object: true,
  ol: true,
  optgroup: true,
  option: true,
  output: true,
  p: true,
  param: true, // Deprecated
  picture: true,
  plaintext: true, // Deprecated
  portal: true, // Experimental
  pre: true,
  progress: true,
  q: true,
  rb: true, // Deprecated
  rp: true,
  rt: true,
  rtc: true, // Deprecated
  ruby: true,
  s: true,
  samp: true,
  script: true,
  search: true,
  section: true,
  select: true,
  slot: true,
  small: true,
  source: true,
  span: true,
  strike: true, // Deprecated
  strong: true,
  style: true,
  sub: true,
  summary: true,
  sup: true,
  table: true,
  tbody: true,
  td: true,
  template: true,
  textarea: true,
  tfoot: true,
  th: true,
  thead: true,
  time: true,
  title: true,
  tr: true,
  track: true,
  tt: true, // Deprecated
  u: true,
  ul: true,
  var: true,
  video: true,
  wbr: true,
  xmp: true
}

export const invalidCustomTags = {
  'annotation-xml': true,
  'color-profile': true,
  'font-face': true,
  'font-face-src': true,
  'font-face-uri': true,
  'font-face-format': true,
  'font-face-name': true,
  'missing-glyph': true
}
