import { waitForHydration } from './helpers.js'
import { test, expect } from '@playwright/test'

test.describe('Nested Imperative Components', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/nested-imperative/')

    await waitForHydration(page)
  })

  test('should load nested components in an imperatively created component', async ({ page }) => {
    // Ensure the parent container rendered
    const parent = page.locator('nested-parent')
    await expect(parent).toBeVisible()

    // Ensure the imperatively appended layout mounted successfully
    const layout = parent.locator('nested-layout')
    await expect(layout).toBeVisible()

    const heading = layout.locator('h1')
    await expect(heading).toHaveText('Nested Layout')

    // Target the button via the deterministic 'ref' suffix generated by the Testing Plugin
    const button = layout.locator('[data-testid$="__btn"]')

    await expect(button).toBeVisible()
    await expect(button).toHaveText('Click Me')

    // Verify imperative interactivity still works
    await button.click()
    await expect(button).toHaveText('Clicked')
  })
})
