name: Test e2e

on:
  - push
  - pull_request

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install

    - name: Build Coralite
      run: pnpm run build

    - name: Build HTML from templates
      run: pnpm  --filter coralite run build-html

    - name: Install Playwright Browser
      run: pnpm --filter coralite exec playwright install firefox --with-deps

    - name: Run Playwright tests
      run: pnpm --filter coralite run test-e2e

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
